### PR TITLE
Made corrections (WIP)

### PR DESCRIPTION
**Pull request by boutilr**
These changes resolve your review comments. However, I still need to update the printed report to include the group quantities. Somewhere after I check the box and click print, m_vReportLines doesn't include grouped quantities. I am currently looking into that.

Also, let me know if you had the same issue with pulling in my changes as last time. It could be due to conflicts between my branch and yours, not allowing you to automatically merge the changes. After resolving the merge conflict it now says "Able to Merge". Perhaps that was the issue.

On a side note, the conflict happened when I merged your changes, which included merging my pull request from last week. I found that odd because there shouldn't be any difference between my branch and yours when you merged my pull request.

### CODE REVIEW

**Comment by RickBrice** [comment]
Group and Total quantities should have the same tabular format.

image

**Comment by boutilr** [comment]
fixed the group quantities. Need to add the summary of quantities

**Comment by boutilr** [comment]
almost done. Need to do some refactoring

**Comment by RickBrice** [comment]
I made a couple minor tweaks to the UI - it wasn't displaying correctly on my screen after your updates. If it no longer looks correct on your screen, we may need to rethink how to set the size of the report header CStatic control in the report dialog.

I think saving the report option is a good idea. There are two methods in CBarlistDoc, LoadDocumentSettings (https://github.com/WSDOT/Barlist/blob/949793670ff4cb1c935e2298416d645d26353146/Barlist/BarlistDoc.cpp#L699) and SaveDocumentSettings (https://github.com/WSDOT/Barlist/blob/949793670ff4cb1c935e2298416d645d26353146/Barlist/BarlistDoc.cpp#L711). These methods save and read values from the registry.

I think the best approach is to read and write a string with GetProfileString and WriteProfileString. The string is a string name for the reporting option. You can interrogate the CBarlistDoc::m_reportOption variable and set the string value or check the string and set the m_reportOption value. The alternative is to use an integer type and get the underlying type of the ReportOption enum class like we discussed a few weeks ago in the Developer Talks - there is a write up of this in the WBFL devdocs folder.

**Pull request merged**
